baseURL = "https://griffinberlste.in/"
languageCode = "en-us"
title = "Griffin Berlstein"
theme = "hyde"
author = "Griffin Berlstein"

[[params.social]]
   name = "github"
   url = "https://github.com/eclecticgriffin"

[[params.social]]
   name = "twitter"
   url = "https://twitter.com/EclecticGriffin"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

[params]
  description = "Musings, Mischief, and Computers"
  layoutReverse = false

[Menus]
  main = [
    {Name = "Blog", URL = "/post" },
    {Name = "Publications", URL = "/papers" }
  ]

  social = [
      {Name = "Github", URL = "https://github.com/eclecticgriffin"},
      {Name = "Twitter", URL = "https://twitter.com/EclecticGriffin"}
  ]

  [permalinks]
    post = "/:year/:month/:day/:title/"