# On every push this script is executed
name: Build and deploy GH Pages
  on:
    push:
      branches:
        - master
  jobs:
    build:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Install and Run Zola
          run: |
            sudo snap install --edge zola
            zola build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
